# Generated by Django 5.0.4 on 2024-04-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_joined_date_player_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='player',
            new_name='playerget',
        ),
    ]
