# Generated by Django 5.0.4 on 2024-06-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dream111',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=10)),
                ('passw', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='dream11',
        ),
    ]
