# Generated by Django 5.0.4 on 2024-06-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0002_dream111_delete_dream11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream111',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
