# Generated by Django 5.0.4 on 2024-06-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0003_alter_dream111_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dream111',
            new_name='dream112',
        ),
    ]
